apiVersion: v1
kind: PersistentVolume
metadata:
  name: brand-local-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
     namespace: default
     name: brand-local-pvc
  hostPath:
    path: "/mnt/data/brandDb"
    type: DirectoryOrCreate